# Generated by Django 6.0.4 on 2026-05-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentfeedback',
            name='generated_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
