# Generated by Django 6.0.4 on 2026-05-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_group', '0002_agentfeedback_generated_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentfeedback',
            name='generated_image_url',
        ),
    ]
