# Generated by Django 6.0.4 on 2026-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_group', '0003_remove_agentfeedback_generated_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='preflightrun',
            name='research_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
