# Generated by Django 6.0.4 on 2026-05-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_group', '0004_preflightrun_research_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentfeedback',
            name='requested_image',
        ),
    ]
