# Generated by Django 6.0.4 on 2026-05-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_group', '0005_remove_agentfeedback_requested_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='preflightrun',
            name='cons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preflightrun',
            name='pros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preflightrun',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
