# Generated by Django 6.0.4 on 2026-05-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_group', '0006_preflightrun_cons_preflightrun_pros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preflightrun',
            name='product_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
