# Generated by Django 6.0.4 on 2026-05-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_group', '0007_preflightrun_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='preflightrun',
            name='pricing_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preflightrun',
            name='upgrade_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
